@baseUrl=http://localhost:8081

@authToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZWZlcmVuY2VfZGF0YV9hcHAiLCJpYXQiOjE3OTAyNDI3NTcsImV4cCI6MTc5MDI0MzY1Nywicm9sZXMiOlsiQVBQX1JFRkVSRU5DRV9EQVRBIl0sImFwcGxpY2F0aW9uIjoicmVmZXJlbmNlLWRhdGEtc2VydmljZSIsImVudmlyb25tZW50IjoibG9jYWwifQ.H8iToWIdwPuhKGX7TLd-Mei3c1zH7-2_f3aTwYLBs5A

###
GET {{baseUrl}}/api/v1/info

###
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "authType": "JWT",
    "consumer": "reference_data_app",
    "email": "reference.data@alramz.ae",
    "consumerPassword": "password123",
    "roles": ["APP_REFERENCE_DATA"],
    "application": "reference-data-service",
    "environment": "local"
}

###
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "consumer": "reference_data_app",
    "consumerPassword": "password123"
}

### Deep Health - Done
GET {{baseUrl}}/api/v1/health/deep
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Get Data From Cache by Key: Done
GET {{baseUrl}}/api/v1/cache/entries/global-config
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Get Cache Status 
GET {{baseUrl}}/api/v1/cache/entries/global-config/status
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Flush Cache: Done
DELETE {{baseUrl}}/api/v1/cache/entries/global-config/flush
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Reaload Cache: Done
POST {{baseUrl}}/api/v1/cache/entries/global-config/reload
Content-Type: application/json
Authorization: Bearer {{authToken}}