spring:
  application:
    name: data-validation-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true

server:
  address: 0.0.0.0
  port: 8080
  host: localhost
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

adapter:
  external-iban-service:
    base-url: https://api.iban.com/clients/api/v4/iban
    api-key: ${IBAN_API_KEY:}
    request-timeout: 10
  external-veriphone-service:
    base-url: https://api.veriphone.io
    api-key: ${VERIPHONE_API_KEY:}
    request-timeout: 10

company:
  scheduler:
    pool-size: 5
    thread-group-name: DataValidation-Scheduled-Tasks
    thread-name-prefix: DataValidation-TaskScheduler-Worker-