spring:
  application:
    name: data-validation-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  host: localhost

sql:
  file: classpath:sql/reference-data-queries.xml,classpath:sql/sql-queries.xml