apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-validation-service
spec:
  replicas: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-validation-service-config
data:
  SPRING_PROFILES_ACTIVE: "preprod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alramz-notification-service
spec:
  replicas: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alramz-notification-service-config
data:
  SPRING_PROFILES_ACTIVE: "preprod"
  APP_EMAIL_SERVICE_PROVIDER: "NOOP"
