-- ===================================================================
-- Create Reference Data Table (Schema Management via Liquibase)
-- ===================================================================
-- liquibase formatted sql
-- changeset liquibase:005-create-reference-data-table.sql:1

CREATE TABLE REFERENCE_DATA (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IDENTIFIER VARCHAR(255) NOT NULL UNIQUE,
    IDENTIFIER_TYPE VARCHAR(255) NOT NULL,
    IDENTIFIER_TEXT VARCHAR(500) NOT NULL,
    STATUS VARCHAR(255)
);

CREATE INDEX idx_identifier ON REFERENCE_DATA(IDENTIFIER);
CREATE INDEX idx_identifier_type ON REFERENCE_DATA(IDENTIFIER_TYPE);
CREATE INDEX idx_status ON REFERENCE_DATA(STATUS);
