apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${SERVICE_NAME}-kv
  namespace: ${NAMESPACE}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ${USER_ASSIGNED_CLIENT_ID}
    keyvaultName: ${KEYVAULT_NAME}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: DB_PASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: ${AZURE_TENANT_ID}
  secretObjects:
    - secretName: ${SERVICE_NAME}-secrets
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: db-password
