apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE_NAME}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: ${TARGET_PORT}
      protocol: TCP
  selector:
    app: ${SERVICE_NAME}
