apiVersion: v1
kind: ConfigMap
metadata:
  name: data-validation-service-config
data:
  SPRING_PROFILES_ACTIVE: "docker"
  COMPANY_DATASOURCE_MIDDLEWARE_URL: "jdbc:postgresql://postgres:5432/alramzmwdb?sslmode=disable"
  COMPANY_DATASOURCE_MIDDLEWARE_USERNAME: "alramzmw"
  COMPANY_DATASOURCE_MIDDLEWARE_DRIVERCLASSNAME: "org.postgresql.Driver"
  COMPANY_DATASOURCE_MIDDLEWARE_STARTUP_VALIDATION_ENABLED: "false"
  COMPANY_DATASOURCE_MIDDLEWARE_POOL_MAXIMUM_POOL_SIZE: "10"
  COMPANY_DATASOURCE_MIDDLEWARE_POOL_MINIMUM_IDLE: "2"
  IBAN_API_KEY: ""
  VERIPHONE_API_KEY: ""
  ETRADE_BASE_URL: "https://etradeqa.alramz.ae"
  ETRADE_CLIENT_ID: "1"
  ETRADE_CLIENT_SECRET: "R@mZS4qR5t"
