apiVersion: v1
kind: Secret
metadata:
  name: data-validation-service-secret
type: Opaque
stringData:
  COMPANY_DATASOURCE_MIDDLEWARE_PLAINPASSWORD: changeme
  JWT_SECRET: defaultSecretKeyChangeMeInProduction1234567890
  CIPHER_PASSWORD: UseMostSecretKey
