apiVersion: v1
kind: ConfigMap
metadata:
  name: alramz-notification-service-config
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:notificationsdb"
  SPRING_DATASOURCE_DRIVER_CLASSNAME: "org.h2.Driver"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_PASSWORD: ""
  APP_EMAIL_SERVICE_PROVIDER: "MICROSOFT_GRAPH"
