apiVersion: v1
kind: Service
metadata:
  name: alramz-notification-service
  labels:
    app: alramz-notification-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: alramz-notification-service
  type: ClusterIP
