apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alramz-preprod
  namespace: argocd
spec:
  project: alramz-platform
  source:
    repoURL: "https://github.com/Gaurav9969351313/alramz-mw-oss.git"
    targetRevision: HEAD
    path: k8s/apps/overlays/preprod
  destination:
    server: https://kubernetes.default.svc
    namespace: alramz-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
