apiVersion: v1
kind: ConfigMap
metadata:
  name: alramz-config
  namespace: alramz-platform
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_DRIVER_CLASSNAME: "org.postgresql.Driver"
  COMPANY_DATASOURCE_MIDDLEWARE_DRIVERCLASSNAME: "org.postgresql.Driver"
  COMPANY_DATASOURCE_MIDDLEWARE_POSTGRES_SSL: "false"
  COMPANY_DATASOURCE_MIDDLEWARE_STARTUP_VALIDATION_ENABLED: "false"
  COMPANY_DATASOURCE_MIDDLEWARE_POOL_MAXIMUM_POOL_SIZE: "10"
  COMPANY_DATASOURCE_MIDDLEWARE_POOL_MINIMUM_IDLE: "2"
  COMPANY_DATASOURCE_MIDDLEWARE_URL: "jdbc:postgresql://postgres:5432/alramzmwdb?sslmode=disable"
  COMPANY_DATASOURCE_BROK_ENABLED: "false"
  COMPANY_LOGGING_SEQ_ENABLED: "true"
  COMPANY_LOGGING_SEQ_URL: "http://seq:80"