apiVersion: v1
kind: Secret
metadata:
  name: alramz-secrets
  namespace: alramz-platform
type: Opaque
stringData:
  POSTGRES_DB: "alramzmwdb"
  POSTGRES_USER: "alramzmw"
  POSTGRES_PASSWORD: "changeme"
  REDIS_PASSWORD: ""
  IBAN_API_KEY: "test-iban-key"
  VERIPHONE_API_KEY: "test-veriphone-key"
  ETRADE_BASE_URL: "https://etradeqa.alramz.ae"
  ETRADE_CLIENT_ID: "test-client-id"
  ETRADE_CLIENT_SECRET: "test-client-secret"
  JWT_SECRET: "mySecretKeyForJWT1234567890123456789012"
  CIPHER_PASSWORD: "UseMostSecretKey"
  AZURE_TENANT_ID: "00000000-0000-0000-0000-000000000000"
  AZURE_CLIENT_ID: "00000000-0000-0000-0000-000000000000"
  AZURE_CLIENT_SECRET: "test-azure-client-secret"
  PGADMIN_DEFAULT_EMAIL: "admin@alramz.ae"
  PGADMIN_DEFAULT_PASSWORD: "admin123"